# Generated by Django 5.1.3 on 2025-01-01 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(5), django.core.validators.RegexValidator(message='Zip code can only contain 5 numbers.', regex='^\\d{5}$')]),
        ),
    ]
