# Generated by Django 5.1.3 on 2025-01-04 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customerinterest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(message='Name can only contain letters, spaces and dashes.', regex='^[a-zA-Z0\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='customerinterest',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customerinterest',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(message='Name can only contain letters and dashes.', regex='^[a-zA-Z0-]+$')]),
        ),
    ]
