# Generated by Django 5.1.3 on 2025-01-05 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customerinterest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(message='Name can only contain letters and dashes.', regex='^[a-zA-Z0-]+$')]),
        ),
    ]
