# Generated by Django 5.1.3 on 2025-01-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_customerinterest_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='method_name',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('text', 'Text'), ('voicemail', 'Voicemail'), ('fax', 'Fax'), ('other', 'Other')], help_text='Preferred Contact Method', max_length=20, unique=True),
        ),
    ]
