# Generated by Django 5.1.3 on 2025-01-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_contactmethod_method_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='method_name',
            field=models.CharField(choices=[('phone', 'Phone'), ('email', 'Email'), ('mail', 'mail'), ('text', 'Text'), ('voicemail', 'Voicemail'), ('fax', 'Fax')], help_text='Preferred Contact Method', max_length=20, unique=True),
        ),
    ]
