# Generated by Django 5.1.3 on 2025-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_contactmethod_method_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmethod',
            name='method_name',
            field=models.CharField(help_text='Preferred Contact Method: phone, email, text, voicemail, etc.', max_length=20, unique=True),
        ),
    ]
