# Generated by Django 5.1.3 on 2025-01-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_contactmethod_method_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinterest',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='customerinterest',
            name='order',
        ),
    ]
