# Generated by Django 5.1.3 on 2025-01-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customerinterest_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinterest',
            old_name='image',
            new_name='icon_image',
        ),
    ]
