# Generated by Django 5.1.3 on 2025-01-19 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_rename_image_customerinterest_icon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='icon_image',
            field=models.FileField(blank=True, default='images/star.svg', null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='customerinterest',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(message='Name can only contain letters, spaces and dashes.', regex='^[a-zA-Z0\\s-]+$')]),
        ),
    ]
