# Generated by Django 5.1.3 on 2025-01-19 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_alter_customerinterest_icon_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(message='Name can only contain letters, spaces, numbers and dashes.', regex='^[a-zA-Z0-9\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='customerinterest',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(20), django.core.validators.RegexValidator(message='Name can only contain letters, numbers and dashes.', regex='^[a-zA-Z0-9-]+$')]),
        ),
    ]
