# Generated by Django 5.1.3 on 2025-01-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_customerinterest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinterest',
            name='icon_image',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
