# Generated by Django 5.1.3 on 2025-01-22 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_customerinterest_icon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='documents',
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer'),
            preserve_default=False,
        ),
    ]
