# Generated by Django 5.1.3 on 2025-01-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_remove_customer_documents_customerdocument_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocument',
            name='file_type',
            field=models.CharField(blank=True, choices=[('w9', 'W-9'), ('soil_test_result', 'Soil Test Result'), ('camp_registration', 'Camp Registration'), ('volunteer_registration', 'Volunteer Registration'), ('cover_crop_application', 'Cover Crop Application'), ('manure_application_record', 'Manure Application Record'), ('seed_tag', 'Seed Tag'), ('other', 'other'), ('lotl_registration', 'LOTL release form'), ('tree_sale_order_form', 'Tree Sale Order From'), ('fish_sale_order_form', 'Fish Sale Order From')], help_text='Select the file type', max_length=30),
        ),
    ]
