# Generated by Django 5.1.3 on 2025-01-23 00:56

import customers.models.relationships
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_customerdocument_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdocument',
            name='file',
            field=models.FileField(upload_to='customer_documents/', validators=[customers.models.relationships.validate_file_type]),
        ),
    ]
