# Generated by Django 5.1.3 on 2025-01-25 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0018_alter_customerdocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.AddField(
            model_name='customernote',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='customers.customer'),
            preserve_default=False,
        ),
    ]
