# Generated by Django 5.1.3 on 2025-01-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0021_customermailinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermailinglist',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='mailing_addresses', to='customers.address'),
        ),
        migrations.AlterField(
            model_name='customermailinglist',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='mailing_interests', to='customers.customerinterest'),
        ),
    ]
