# Generated by Django 5.1.3 on 2025-02-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0022_alter_customermailinglist_addresses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermailinglist',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='mailing_lists', to='customers.customer'),
        ),
    ]
