# Generated by Django 5.1.3 on 2025-02-02 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0023_customermailinglist_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermailinglist',
            name='name',
            field=models.CharField(help_text="Name of Mailing List: 'Fish Sale', 'Summer Camp' if based on interest or a custom name.", max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(message='Name can only contain letters, spaces, numbers and dashes.', regex='^[a-zA-Z0-9\\s-]+$')]),
        ),
    ]
