# Generated by Django 5.1.3 on 2025-02-02 17:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0024_alter_customermailinglist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermailinglist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='customermailinglist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customermailinglist',
            name='name',
            field=models.CharField(help_text="Mailing List Name: 'Fish Sale', 'Summer Camp' (if based on an interest) or a custom name", max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(message='Name can only contain letters, spaces, numbers and dashes.', regex='^[a-zA-Z0-9\\s-]+$')]),
        ),
    ]
