# Generated by Django 5.1.3 on 2025-02-07 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0025_alter_customermailinglist_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_note', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('customer_note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_history', to='customers.customernote')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_authors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
