# Generated by Django 5.1.3 on 2025-02-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0026_customernotehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='likedcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likedcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likedcustomer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='likedcustomer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='likedreply',
            name='CustomUser',
        ),
        migrations.RemoveField(
            model_name='likedreply',
            name='reply',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='LikedComment',
        ),
        migrations.DeleteModel(
            name='LikedCustomer',
        ),
        migrations.DeleteModel(
            name='LikedReply',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
