# Generated by Django 5.1.3 on 2025-01-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
        ('customers', '0002_alter_address_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Select your interests', related_name='users_with_interest', to='customers.customerinterest'),
        ),
    ]
