# Generated by Django 5.1.3 on 2025-01-04 17:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='The lack of power to take joy in outdoor nature is as real a misfortune as the lack of power to take joy in books. --T. Roosevelt.', null=True, validators=[django.core.validators.MaxLengthValidator(500), django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and common punctuation are allowed. Max 500 characters.', regex='^[a-zA-Z0-9\\s.!?,-:;]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=75, validators=[django.core.validators.MaxLengthValidator(75), django.core.validators.RegexValidator(message='Name can only contain letters, numbers and dashes.', regex='^[a-zA-Z0-9\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='job_title',
            field=models.CharField(blank=True, default='Conservation Specialist', max_length=75, null=True, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.RegexValidator(message='Job Description can only contain letters and dashes.', regex='^[a-zA-Z\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=75, validators=[django.core.validators.MaxLengthValidator(75), django.core.validators.RegexValidator(message='Name can only contain letters and dashes.', regex='^[a-zA-Z\\s-]+$')]),
        ),
    ]
