# Generated by Django 5.1.3 on 2025-01-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_alter_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
