# Generated by Django 5.1.3 on 2025-01-12 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=75, validators=[django.core.validators.MaxLengthValidator(75), django.core.validators.RegexValidator(message='Name can only contain letters, numbers and dashes.', regex='^[a-zA-Z0-9\\s-]+$')]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, validators=[django.core.validators.MaxLengthValidator(75), django.core.validators.RegexValidator(message='Name can only contain letters and dashes.', regex='^[a-zA-Z\\s-]+$')]),
        ),
    ]
